
package view;

import javax.swing.JOptionPane;
import model.Student;
import javax.swing.table.DefaultTableModel;
import model.Student;
import logicservices.studentservice;
public class Register extends javax.swing.JFrame {

   int studentid;
   
   
   studentservice serve=new studentservice();
   public Register() { ///////دا للاضافة
    initComponents();
    studentid = -1; // معناها ADD
}


public Register( int id,String name, int age, double gpa, int dept) { /////////// دا للتعديل 
    initComponents();
    
   this.studentid=id;
    t1.setText(name);
    t2.setText(String.valueOf(age));
    t3.setText(String.valueOf(gpa));
    t4.setText(String.valueOf(dept));
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 6, 329, 42));

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 81, 329, 37));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 154, 329, 41));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 232, 329, 40));

        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 19, -1, -1));

        jLabel2.setText("major");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 91, -1, -1));

        jLabel3.setText("GPA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 166, -1, -1));

        jLabel4.setText("Departemnet");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 244, -1, -1));

        jButton1.setText("ADD");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 330, -1, -1));

        b2.setText("Update");
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
        });
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
  try{
      Student s=new Student(
        t1.getText(),
            Integer.parseInt(t2.getText()),
            Double.parseDouble(t3.getText()),
            Integer.parseInt(t4.getText())
        );
        serve.add(s);
        JOptionPane.showMessageDialog(this,"added succesfully");
  }
catch(Exception e){System.out.println(e);}  
    }//GEN-LAST:event_jButton1MouseClicked

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
        try{
        String n = t1.getText();
        int age=Integer.parseInt(t2.getText());
        double gpa=Double.parseDouble(t3.getText());
        int d = Integer.parseInt(t4.getText());
        Student s=new Student(n,age,gpa,d); 
        serve.update(s);
        JOptionPane.showMessageDialog(this, "updated sucssfully");
        }
        catch(Exception e){System.out.println(e);}        
        
        
        
        
//        try{
//
//String url="jdbc:mysql://localhost:3306/university";
//     String user= "root";
//     String pass="ramezemad";
//     
//     Connection con = DriverManager.getConnection(url,user,pass);
//     
//     if(studentid!=-1){
//PreparedStatement ps=con.prepareStatement("UPDATE students SET name = ?, age = ?, gpa = ?, dept = ? WHERE id = ?;");
//      ps.setString(1, t1.getText());
//      ps.setInt(2, Integer.parseInt(t2.getText()));
//      ps.setDouble(3,Double.parseDouble(t3.getText()));
//      ps.setInt(4, Integer.parseInt(t4.getText()));
//      ps.setInt(5,studentid);
//       ps.executeUpdate();
//          }
//     
//     else{  JOptionPane.showMessageDialog(this,"you have to choose ID to update");}
//     
//      }
//catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_b2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
              java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JTextField t1;
    public javax.swing.JTextField t2;
    public javax.swing.JTextField t3;
    public javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
